//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webnangcao1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdon
    {
        public int Madonhang { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> thanhtien { get; set; }
        public string Masanpham { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
