//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webnangcao1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class chitietdon
    {
        [DisplayName("Mã đơn hàng")]
        public int Madonhang { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> soluong { get; set; }
        [DisplayName("Số tiền")]
        public Nullable<int> thanhtien { get; set; }
        [DisplayName("Mã sản phẩm")]
        public string Masanpham { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
