//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webnangcao1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class donhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donhang()
        {
            this.chitietdons = new HashSet<chitietdon>();
        }
        [Required(ErrorMessage = "Mã đơn hàng bắt buộc phải nhập")]
        [DisplayName("Mã đơn hàng")]
        public int Madonhang { get; set; }
        [Required(ErrorMessage = "Tên tài khoản bắt buộc phải nhập")]
        [DisplayName("Tên đơn hàng")]
        public string Tentaikhoan { get; set; }
        [DisplayName("Trạng thái thanh toán đơn hàng")]
        public Nullable<int> dathanhtoan { get; set; }
        [DisplayName("Trạng thái đặt đơn hàng")]
        public Nullable<int> tinhtrangdathang { get; set; }
        [DisplayName("Ngày đặt")]
        [DataType(DataType.Date, ErrorMessage = "Dữ liệu không đúng định dạng")]
        public Nullable<System.DateTime> ngaydat { get; set; }
        [DisplayName("Ngày giao")]
        [DataType(DataType.Date, ErrorMessage = "Dữ liệu không đúng định dạng")]
        public Nullable<System.DateTime> ngaygiao { get; set; }
    
        public virtual taikhoan taikhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdon> chitietdons { get; set; }
    }
}
